# For safety, the databases are not exposed to local machine, only to the container group.

services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: [ "redis-server", "--requirepass", "$REDIS_PASSWORD" ]
    expose:
      - 6379
    restart: unless-stopped

  express:
    build:
      context: .
      dockerfile: express.Dockerfile
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
