name: Run unit tests on production Docker

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up mock .env file
        run: |
          echo "NODE_ENV=production" >> .env
          echo "PORT=8080" >> .env
          echo "POSTGRES_PASSWORD=postgres" >> .env
          echo "REDIS_PASSWORD=redis" >> .env
          echo "CLEANUP_STARTED_MATCHES=true" >> .env
          echo "KEEP_LOGS_DAYS=14" >> .env

      - name: Build and start Docker containers
        run: |
          docker compose -f docker-compose.prod.yml up --build express -d

      - name: Run unit tests
        run: |
          docker compose exec express npm test

      - name: Shutdown containers
        run: |
          docker compose down
